#
# ESLint Configuration, https://eslint.org/docs/user-guide/configuring
#

plugins:
  - "jest"
  - "react"
  - "flowtype"

extends:
  - "airbnb"
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - "plugin:flowtype/recommended"

env:
  browser: true
  es6: true
  node: true
  jest: true

globals:
  __DEV_TOOLS__: true

parserOptions:
  ecmaVersion: 6
  impliedStrict: true # All code will be treated as being in strict mode.
  sourceType: "module" # Indicates that we are using ES6 modules.

rules:
  react/jsx-uses-react: "error"
  react/jsx-uses-vars: "error"
  react/react-in-jsx-scope: "error"
  react/jsx-indent: "off"
  react/prefer-stateless-function: "off"
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".jsx"
        - ".test.js"
  react/sort-comp:
    - 1
    - order:
        - 'defaultProps'
        - 'state'
        - 'type-annotations'
        - 'instance-variables'
        - 'constructor'
        - 'everything-else'
        - 'lifecycle'
        - '/^(on|handle).+$/'
        - 'instance-methods'
        - 'render'

  new-cap: "off"
  valid-jsdoc: "error"
  import/no-extraneous-dependencies: "off"
  import/no-named-as-default: "off"
  no-var: "off"
  vars-on-top: "off"
  comma-dangle: "off"
  id-length: "off"

  indent:
    - "error"
    - 2
    - SwitchCase: 1

