root: true
processors:
  - "stylelint-processor-styled-components"
extends:
  - "stylelint-config-standard"
  - "stylelint-config-sass-guidelines"
  - "stylelint-config-styled-components"
rules:
  max-nesting-depth: 5
  no-eol-whitespace:
    - true
    - ignore:
       - "empty-lines"
  order/properties-alphabetical-order: null
  scss/at-extend-no-missing-placeholder: null
  selector-no-qualifying-type:
    - true
    - ignore:
      - class
  function-url-quotes: null
  string-quotes: "single"
  value-no-vendor-prefix: true
  declaration-empty-line-before:
    - "never"
    -
      ignore:
        - "after-declaration"

